# User.create!([
#   { first_name: "Jess", last_name: "White", email: "jess@aol.com", password_digest: "password", active: true },
#   { first_name: "Jemima", last_name: "Jones", email: "jj@aol.com", password_digest: "password", active: true },
#   { first_name: "Mike", last_name: "McFaddin", email: "mikemcfaddin@email.com", password_digest: "password", active: true },
# ])

# Organization.create!([
#   { name: "Middle Eastern Immigrant and Refugee Alliance (MIRA)" },
# ])

# OrganizationUser.create!([
#   { organization_id: 1, user_id: 3 },
# ])

# Bio.create!([
#   { organization_id: 1, first_name: "Laura", last_name: "Youngberg", text: "<p><span style=\"color: rgba(0, 0, 0, 0.9);\">Laura has served as director of MIRA since 2014. Her mission-driven leadership includes both financial and administrative responsibility for a social service organization serving over 800 Middle Eastern refugees and immigrants annually. Includes application, reporting, renewal, and management of private, state, and federal grants. Responsible for hiring, evaluation, and management of staff of 7. Doubled staff size and budget in 3 years. Expertise in leading in a multicultural environment, with colleagues and clients who are non-native English speakers and come from diverse social, educational, religious, and ethnic backgrounds.</span></p>", title: "Executive Director", wordcount: 93 },
#   { organization_id: 1, first_name: "Jess", last_name: "White", text: "<p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library. </p>", title: "Grantwriter, Web Developer", wordcount: 66 },
#   { organization_id: 1, first_name: "Michael", last_name: "McFaddin", text: "<p>Mike McFaddin's web development experience includes a full-stack certification as well as several additional months of web development projects. Mike has been collaborating on the creation and implementation of an original grantwriting app at MIRA for the past several months. Mike also has extensive experience in graphic design, events planning, and community outreach. </p>", title: "Web Developer", wordcount: 54 },
# ])

# FundingOrg.create!([
#   { website: "https://www.acf.hhs.gov/orr", name: "Office of Refugee Resettlement", organization_id: 1 },
#   { website: "https://www.dhs.gov/", name: "Department of Homeland Security", organization_id: 1 },
#   { website: "https://www.heartlandalliance.org/", name: "Heartland Alliance", organization_id: 1 },
#   { website: "https://www.hadassah.org/", name: "Hadassah", organization_id: 1 },
#   { website: "https://www.cct.org/about/partnerships_initiatives/asian-giving-circle/", name: "Asian Giving Circle", organization_id: 1 },
# ])

# Category.create!([
#   { organization_id: 1, name: "General Purpose" },
#   { organization_id: 1, name: "Financial Literacy" },
#   { organization_id: 1, name: "Gender Equality" },
#   { organization_id: 1, name: "Family Services" },
#   { organization_id: 1, name: "Cultural and Community Programming" },
#   { organization_id: 1, name: "Education" },
#   { organization_id: 1, name: "Citizenship and Naturalization" },
#   { organization_id: 1, name: "Legal Aid" },
# ])

# Grant.create!([
#   { organization_id: 1, title: "Letter of Interest: Asian Giving Circle Grants 2020", funding_org_id: 4, rfp_url: "https://www.cct.org/about/partnerships_initiatives/asian-giving-circle/", deadline: "2020-11-13 01:45:00", submitted: true, successful: true, purpose: "general funding" },
#   { organization_id: 1, title: "Test UserFlow for Sections", funding_org_id: 3, rfp_url: "userflow.org", deadline: "2020-11-20 13:31:00", submitted: false, successful: false, purpose: "general funding" },
#   { organization_id: 1, title: "Test null values for sort order", funding_org_id: 1, rfp_url: "null.ord", deadline: "2020-11-26 12:52:00", submitted: false, successful: false, purpose: "general funding" },
#   { organization_id: 1, title: "Test Grant Sort Order Logic", funding_org_id: 1, rfp_url: "Logic.org", deadline: "2020-11-18 13:07:00", submitted: false, successful: false, purpose: "general funding" },
# ])

# Boilerplate.create!([
#   { organization_id: 1, category_id: 1, title: "Mission", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p>", wordcount: 219 },
#   { organization_id: 1, category_id: 1, title: "What We Do", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", wordcount: 146 },
#   { organization_id: 1, category_id: 5, title: "Community Engagement and Empowerment Programs", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", wordcount: 53 },
#   { organization_id: 1, category_id: 4, title: "Case Management Program", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA helps Middle Eastern refugees and immigrants access the services they need, including public benefits, healthcare, and referrals to partner organizations or other agencies. In FY18-19 MIRA provided 341 Case Management Clients with 677 Case Management Case Activities.</span></p>", wordcount: 42 },
#   { organization_id: 1, category_id: 4, title: "Assistance for Families With Children", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</span></p>", wordcount: 51 },
#   { organization_id: 1, category_id: 1, title: "Adult Education Guidance Program", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA works with clients to address their educational needs, including assistance applying for college credit and training programs, evaluating educational credentials, and applying for financial aid. In FY18-19 MIRA provided 97 Adult Education Clients with 152 Adult Education Case Activities.</span></p>", wordcount: 44 },
#   { organization_id: 1, category_id: 1, title: "Immigration Legal Services", text: "<p><span style=\"color: rgb(102, 102, 102);\">The MIRA Immigration Legal Services Program assists with naturalization petitions and green card applications.&nbsp;There is no fee for the service, although application fees still apply. In FY18-19 MIRA assisted 240 clients with immigration legal services.</span></p>", wordcount: 39 },
# ])

# Section.create!([
#   { grant_id: 1, title: "Overview of the Organization", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p>", sort_order: 1, wordcount: 219 },
#   { grant_id: 1, title: "Program Goals", text: "<p>At the beginning of 2020, a consultation among MIRA Board, Staff, and Community Members identified three primary areas for growth: Women and Children’s Empowerment, Legal Clinic Services, and Mental Health Promotion.&nbsp;While these are existing program areas, the goal for the organization is to align staff skills and training, funding resources, and community engagement to establish MIRA as the leader for these programs for Middle Eastern immigrants and refugees on the north side of Chicago.</p>", sort_order: 2, wordcount: 74 },
#   { grant_id: 1, title: "Programs", text: "<p>MIRA has provided the following services to over 600 clients and their families, with a total impact of about 1000 immigrants and refugees, in the last fiscal year (July 18 – June 19):</p><p><br></p><p>Community Engagement and Empowerment Programs:&nbsp;MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In&nbsp;FY18-19, 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</p><p><br></p><p>Case Management Program:&nbsp;MIRA helps Middle Eastern refugees and immigrants access the services they need, including public benefits, healthcare, and referrals to partner organizations or other agencies. In FY18-19 MIRA provided 341 Case Management Clients with 677 Case Management Case Activities.</p><p><br></p><p>Assistance for Families with Children: MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</p><p><br></p><p>Adult Education Guidance Program:&nbsp;MIRA works with clients to address their educational needs, including assistance applying for college credit and training programs, evaluating educational credentials, and applying for financial aid. In FY18-19 MIRA provided 97 Adult Education Clients with 152 Adult Education Case Activities.</p><p><br></p><p>Immigration Legal Services:&nbsp;The MIRA Immigration Legal Services Program assists with naturalization petitions and green card applications.&nbsp;There is no fee for the service, although application fees still apply. In FY18-19 MIRA assisted 240 clients with immigration legal services.</p>", sort_order: 3, wordcount: 252 },
#   { grant_id: 1, title: "Overview of the Proposed Program/Project", text: "<p>MIRA proposes the continuation of the Mental Health First Aid program funded through the Asian Giving Circle for 2019-20.&nbsp;In light of the current pandemic, isolation, and deaths, MIRA projects that the need for increased Mental Health awareness and education in the Middle Eastern immigrant and refugee community will continue to expand and it is vital to train more members of the community to provide Mental Health First Aid in the coming months.&nbsp;The goal of the proposed program is to educate and empower area community members to identify mental health issues in the community and provide referrals and resources to support refugee and immigrant community members in seeking mental health services. Mental Health First Aid is an evidence-based CDC-reviewed public education program that introduces participants to risk factors and warning signs of mental illnesses, builds understanding of their impact, and overviews common supports. This training course uses role-playing and simulations to demonstrate how to offer initial help in a mental health crisis and connect persons to the appropriate professional, peer, social, and self-help care. The program also teaches the common risk factors and warning signs of specific types of illnesses, like anxiety, depression, substance use, bipolar disorder, eating disorders, and schizophrenia. &nbsp;</p>", sort_order: 4, wordcount: 201 },
#   { grant_id: 1, title: "Leaders of the Program/Project: ", text: "<p>Ekram Hanna, MIRA Community Engagement Manager, Certified Mental Health First Aid Trainer</p>", sort_order: 5, wordcount: 12 },
#   { grant_id: 1, title: "How the Program/Project Directly Relates to Community Organizing, Civic Engagement, and/or Healing in AAPI communities", text: "<p>With the introduction of a new shorter (4 hour) course, MIRA staff can engage more community members directly in training and raising awareness of mental health issues at a time when isolation, depression, and catastrophic losses will be affecting the entire country, and have the potential to devastate the newly developing Middle Eastern immigrant and refugee community on the north side of Chicago.</p>", sort_order: 6, wordcount: 63 },
#   { grant_id: 1, title: "What would success look like to the organization for this Program/Project (please describe one or more indicators)? ", text: "<p>We will measure the success of these programs in terms of the volume and quality of the services we provide to our clients. We will provide this specialized training program at least four times over the course of the next year, in conjunction with a national training program that provides pre- and post-training testing on issues related to mental health awareness and treatment. As a result of this enhanced level of awareness among community members, we anticipate a higher level of referrals to mental health services ranging from counseling to substance-abuse recovery support to intimate partner violence services. We also anticipate an increased openness regarding these topics among our clients, including in their discussions with staff. Since we are an organization that emphasizes client-led coaching and peer support, we also anticipate more effective dialogues between staff members and clients seeking services at MIRA. We will also use our experience with this training to partner with other local agencies and address mental health issues collaboratively.</p>", sort_order: 7, wordcount: 164 },
#   { grant_id: 4, title: "Test Section 3", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 3, wordcount: 146 },
#   { grant_id: 2, title: "Organization Overview", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p><p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 1, wordcount: 364 },
#   { grant_id: 2, title: "Test Section 2", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 2, wordcount: 284 },
#   { grant_id: 3, title: "Test Section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p><p><br></p><p>Laura Youngberg:</p><p><span style=\"color: rgba(0, 0, 0, 0.9);\">Laura has served as director of MIRA since 2014. Her mission-driven leadership includes both financial and administrative responsibility for a social service organization serving over 800 Middle Eastern refugees and immigrants annually. Includes application, reporting, renewal, and management of private, state, and federal grants. Responsible for hiring, evaluation, and management of staff of 7. Doubled staff size and budget in 3 years. Expertise in leading in a multicultural environment, with colleagues and clients who are non-native English speakers and come from diverse social, educational, religious, and ethnic backgrounds.</span></p>", sort_order: 1, wordcount: 239 },
#   { grant_id: 4, title: "Test Section 2", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 2, wordcount: 211 },
#   { grant_id: 4, title: "Test Section 4", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 4, wordcount: 118 },
#   { grant_id: 4, title: "Test Section 5", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 5, wordcount: 118 },
#   { grant_id: 4, title: "Test Section 6", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 6, wordcount: 116 },
#   { grant_id: 4, title: "Test Section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library. This edits also. this edits also and these edits.</p>", sort_order: 1, wordcount: 127 },
# ])

# Report.create!([
#   { grant_id: 1, title: "Letter of Interest: Asian Giving Circle Grants 2020", deadline: "2020-11-24 12:49:00", submitted: false },
#   { grant_id: 1, title: "", deadline: "2020-11-11 23:52:00", submitted: false },
#   { grant_id: 1, title: "Report for Letter of Interest: Asian Giving Circle Grants 2020", deadline: "2020-11-25 12:53:00", submitted: false },
#   { grant_id: 1, title: "Asian Giving Circle Grant Report", deadline: "2020-11-24 11:07:00", submitted: true },
#   { grant_id: 1, title: "Report for Letter of Interest: Asian Giving Circle Grants 2020", deadline: "2020-11-17 13:54:00", submitted: false },
#   { grant_id: 4, title: "Report for Test Grant Sort Order Logic", deadline: "2020-11-17 13:09:00", submitted: false },
# ])
# ReportSection.create!([
#   { report_id: 1, title: "Report Intro", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p>", sort_order: 1, wordcount: 0 },
#   { report_id: 1, title: "Program Achievements", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 2, wordcount: 0 },
#   { report_id: 5, title: "Test Report section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 1, wordcount: 0 },
#   { report_id: 5, title: "Test Report Section 4", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA helps Middle Eastern refugees and immigrants access the services they need, including public benefits, healthcare, and referrals to partner organizations or other agencies. In FY18-19 MIRA provided 341 Case Management Clients with 677 Case Management Case Activities.</span></p>", sort_order: 4, wordcount: 0 },
#   { report_id: 5, title: "Test Report Section 7", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 7, wordcount: 0 },
#   { report_id: 5, title: "Test Report Section 2", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 2, wordcount: 0 },
#   { report_id: 6, title: "Test Report Section 3", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</span></p>", sort_order: 3, wordcount: 0 },
#   { report_id: 6, title: "Test Report Section 5", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 5, wordcount: 0 },
#   { report_id: 6, title: "Test Report Section 2", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA works with clients to address their educational needs, including assistance applying for college credit and training programs, evaluating educational credentials, and applying for financial aid. In FY18-19 MIRA provided 97 Adult Education Clients with 152 Adult Education Case Activities.</span></p>", sort_order: 2, wordcount: 0 },
#   { report_id: 6, title: "Test Report Section 4", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</span></p>", sort_order: 4, wordcount: 51 },
#   { report_id: 6, title: "Test Section 2", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 2, wordcount: 53 },
#   { report_id: 6, title: "Test Section 2", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 2, wordcount: 53 },
#   { report_id: 6, title: "Test Section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA helps Middle Eastern refugees and immigrants access the services they need, including public benefits, healthcare, and referrals to partner organizations or other agencies. In FY18-19 MIRA provided 341 Case Management Clients with 677 Case Management Case Activities.</span></p>", sort_order: 1, wordcount: 42 },
#   { report_id: 5, title: "Test Section Layout", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 6, wordcount: 146 },
#   { report_id: 6, title: "Test Report Section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities. Will this update&gt; Will this test work?</span></p>", sort_order: 1, wordcount: 60 },
# ])


# User.create!([
#   { first_name: "Jess", last_name: "White", email: "jess@aol.com", password_digest: "password", active: true },
#   { first_name: "Jemima", last_name: "Jones", email: "jj@aol.com", password_digest: "password", active: true },
#   { first_name: "Mike", last_name: "McFaddin", email: "mikemcfaddin@email.com", password_digest: "password", active: true },
# ])

# Organization.create!([
#   { name: "Middle Eastern Immigrant and Refugee Alliance (MIRA)" },
# ])

# OrganizationUser.create!([
#   { organization_id: 1, user_id: 3 },
# ])

# Bio.create!([
#   { organization_id: 1, first_name: "Laura", last_name: "Youngberg", text: "<p><span style=\"color: rgba(0, 0, 0, 0.9);\">Laura has served as director of MIRA since 2014. Her mission-driven leadership includes both financial and administrative responsibility for a social service organization serving over 800 Middle Eastern refugees and immigrants annually. Includes application, reporting, renewal, and management of private, state, and federal grants. Responsible for hiring, evaluation, and management of staff of 7. Doubled staff size and budget in 3 years. Expertise in leading in a multicultural environment, with colleagues and clients who are non-native English speakers and come from diverse social, educational, religious, and ethnic backgrounds.</span></p>", title: "Executive Director", wordcount: 93 },
#   { organization_id: 1, first_name: "Jess", last_name: "White", text: "<p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library. </p>", title: "Grantwriter, Web Developer", wordcount: 66 },
#   { organization_id: 1, first_name: "Michael", last_name: "McFaddin", text: "<p>Mike McFaddin's web development experience includes a full-stack certification as well as several additional months of web development projects. Mike has been collaborating on the creation and implementation of an original grantwriting app at MIRA for the past several months. Mike also has extensive experience in graphic design, events planning, and community outreach. </p>", title: "Web Developer", wordcount: 54 },
# ])

# FundingOrg.create!([
#   { website: "https://www.acf.hhs.gov/orr", name: "Office of Refugee Resettlement", organization_id: 1 },
#   { website: "https://www.dhs.gov/", name: "Department of Homeland Security", organization_id: 1 },
#   { website: "https://www.heartlandalliance.org/", name: "Heartland Alliance", organization_id: 1 },
#   { website: "https://www.hadassah.org/", name: "Hadassah", organization_id: 1 },
#   { website: "https://www.cct.org/about/partnerships_initiatives/asian-giving-circle/", name: "Asian Giving Circle", organization_id: 1 },
# ])

# Category.create!([
#   { organization_id: 1, name: "General Purpose" },
#   { organization_id: 1, name: "Financial Literacy" },
#   { organization_id: 1, name: "Gender Equality" },
#   { organization_id: 1, name: "Family Services" },
#   { organization_id: 1, name: "Cultural and Community Programming" },
#   { organization_id: 1, name: "Education" },
#   { organization_id: 1, name: "Citizenship and Naturalization" },
#   { organization_id: 1, name: "Legal Aid" },
# ])

# Grant.create!([
#   { organization_id: 1, title: "Letter of Interest: Asian Giving Circle Grants 2020", funding_org_id: 4, rfp_url: "https://www.cct.org/about/partnerships_initiatives/asian-giving-circle/", deadline: "2020-11-13 01:45:00", submitted: true, successful: true, purpose: "general funding" },
#   { organization_id: 1, title: "Test UserFlow for Sections", funding_org_id: 3, rfp_url: "userflow.org", deadline: "2020-11-20 13:31:00", submitted: false, successful: false, purpose: "general funding" },
#   { organization_id: 1, title: "Test null values for sort order", funding_org_id: 1, rfp_url: "null.ord", deadline: "2020-11-26 12:52:00", submitted: false, successful: false, purpose: "general funding" },
#   { organization_id: 1, title: "Test Grant Sort Order Logic", funding_org_id: 1, rfp_url: "Logic.org", deadline: "2020-11-18 13:07:00", submitted: false, successful: false, purpose: "general funding" },
# ])

# Boilerplate.create!([
#   { organization_id: 1, category_id: 1, title: "Mission", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p>", wordcount: 219 },
#   { organization_id: 1, category_id: 1, title: "What We Do", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", wordcount: 146 },
#   { organization_id: 1, category_id: 5, title: "Community Engagement and Empowerment Programs", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", wordcount: 53 },
#   { organization_id: 1, category_id: 4, title: "Case Management Program", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA helps Middle Eastern refugees and immigrants access the services they need, including public benefits, healthcare, and referrals to partner organizations or other agencies. In FY18-19 MIRA provided 341 Case Management Clients with 677 Case Management Case Activities.</span></p>", wordcount: 42 },
#   { organization_id: 1, category_id: 4, title: "Assistance for Families With Children", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</span></p>", wordcount: 51 },
#   { organization_id: 1, category_id: 1, title: "Adult Education Guidance Program", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA works with clients to address their educational needs, including assistance applying for college credit and training programs, evaluating educational credentials, and applying for financial aid. In FY18-19 MIRA provided 97 Adult Education Clients with 152 Adult Education Case Activities.</span></p>", wordcount: 44 },
#   { organization_id: 1, category_id: 1, title: "Immigration Legal Services", text: "<p><span style=\"color: rgb(102, 102, 102);\">The MIRA Immigration Legal Services Program assists with naturalization petitions and green card applications.&nbsp;There is no fee for the service, although application fees still apply. In FY18-19 MIRA assisted 240 clients with immigration legal services.</span></p>", wordcount: 39 },
# ])

# Section.create!([
#   { grant_id: 1, title: "Overview of the Organization", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p>", sort_order: 1, wordcount: 219 },
#   { grant_id: 1, title: "Program Goals", text: "<p>At the beginning of 2020, a consultation among MIRA Board, Staff, and Community Members identified three primary areas for growth: Women and Children’s Empowerment, Legal Clinic Services, and Mental Health Promotion.&nbsp;While these are existing program areas, the goal for the organization is to align staff skills and training, funding resources, and community engagement to establish MIRA as the leader for these programs for Middle Eastern immigrants and refugees on the north side of Chicago.</p>", sort_order: 2, wordcount: 74 },
#   { grant_id: 1, title: "Programs", text: "<p>MIRA has provided the following services to over 600 clients and their families, with a total impact of about 1000 immigrants and refugees, in the last fiscal year (July 18 – June 19):</p><p><br></p><p>Community Engagement and Empowerment Programs:&nbsp;MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In&nbsp;FY18-19, 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</p><p><br></p><p>Case Management Program:&nbsp;MIRA helps Middle Eastern refugees and immigrants access the services they need, including public benefits, healthcare, and referrals to partner organizations or other agencies. In FY18-19 MIRA provided 341 Case Management Clients with 677 Case Management Case Activities.</p><p><br></p><p>Assistance for Families with Children: MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</p><p><br></p><p>Adult Education Guidance Program:&nbsp;MIRA works with clients to address their educational needs, including assistance applying for college credit and training programs, evaluating educational credentials, and applying for financial aid. In FY18-19 MIRA provided 97 Adult Education Clients with 152 Adult Education Case Activities.</p><p><br></p><p>Immigration Legal Services:&nbsp;The MIRA Immigration Legal Services Program assists with naturalization petitions and green card applications.&nbsp;There is no fee for the service, although application fees still apply. In FY18-19 MIRA assisted 240 clients with immigration legal services.</p>", sort_order: 3, wordcount: 252 },
#   { grant_id: 1, title: "Overview of the Proposed Program/Project", text: "<p>MIRA proposes the continuation of the Mental Health First Aid program funded through the Asian Giving Circle for 2019-20.&nbsp;In light of the current pandemic, isolation, and deaths, MIRA projects that the need for increased Mental Health awareness and education in the Middle Eastern immigrant and refugee community will continue to expand and it is vital to train more members of the community to provide Mental Health First Aid in the coming months.&nbsp;The goal of the proposed program is to educate and empower area community members to identify mental health issues in the community and provide referrals and resources to support refugee and immigrant community members in seeking mental health services. Mental Health First Aid is an evidence-based CDC-reviewed public education program that introduces participants to risk factors and warning signs of mental illnesses, builds understanding of their impact, and overviews common supports. This training course uses role-playing and simulations to demonstrate how to offer initial help in a mental health crisis and connect persons to the appropriate professional, peer, social, and self-help care. The program also teaches the common risk factors and warning signs of specific types of illnesses, like anxiety, depression, substance use, bipolar disorder, eating disorders, and schizophrenia. &nbsp;</p>", sort_order: 4, wordcount: 201 },
#   { grant_id: 1, title: "Leaders of the Program/Project: ", text: "<p>Ekram Hanna, MIRA Community Engagement Manager, Certified Mental Health First Aid Trainer</p>", sort_order: 5, wordcount: 12 },
#   { grant_id: 1, title: "How the Program/Project Directly Relates to Community Organizing, Civic Engagement, and/or Healing in AAPI communities", text: "<p>With the introduction of a new shorter (4 hour) course, MIRA staff can engage more community members directly in training and raising awareness of mental health issues at a time when isolation, depression, and catastrophic losses will be affecting the entire country, and have the potential to devastate the newly developing Middle Eastern immigrant and refugee community on the north side of Chicago.</p>", sort_order: 6, wordcount: 63 },
#   { grant_id: 1, title: "What would success look like to the organization for this Program/Project (please describe one or more indicators)? ", text: "<p>We will measure the success of these programs in terms of the volume and quality of the services we provide to our clients. We will provide this specialized training program at least four times over the course of the next year, in conjunction with a national training program that provides pre- and post-training testing on issues related to mental health awareness and treatment. As a result of this enhanced level of awareness among community members, we anticipate a higher level of referrals to mental health services ranging from counseling to substance-abuse recovery support to intimate partner violence services. We also anticipate an increased openness regarding these topics among our clients, including in their discussions with staff. Since we are an organization that emphasizes client-led coaching and peer support, we also anticipate more effective dialogues between staff members and clients seeking services at MIRA. We will also use our experience with this training to partner with other local agencies and address mental health issues collaboratively.</p>", sort_order: 7, wordcount: 164 },
#   { grant_id: 4, title: "Test Section 3", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 3, wordcount: 146 },
#   { grant_id: 2, title: "Organization Overview", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p><p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 1, wordcount: 364 },
#   { grant_id: 2, title: "Test Section 2", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 2, wordcount: 284 },
#   { grant_id: 3, title: "Test Section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p><p><br></p><p>Laura Youngberg:</p><p><span style=\"color: rgba(0, 0, 0, 0.9);\">Laura has served as director of MIRA since 2014. Her mission-driven leadership includes both financial and administrative responsibility for a social service organization serving over 800 Middle Eastern refugees and immigrants annually. Includes application, reporting, renewal, and management of private, state, and federal grants. Responsible for hiring, evaluation, and management of staff of 7. Doubled staff size and budget in 3 years. Expertise in leading in a multicultural environment, with colleagues and clients who are non-native English speakers and come from diverse social, educational, religious, and ethnic backgrounds.</span></p>", sort_order: 1, wordcount: 239 },
#   { grant_id: 4, title: "Test Section 2", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 2, wordcount: 211 },
#   { grant_id: 4, title: "Test Section 4", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 4, wordcount: 118 },
#   { grant_id: 4, title: "Test Section 5", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 5, wordcount: 118 },
#   { grant_id: 4, title: "Test Section 6", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library.</p>", sort_order: 6, wordcount: 116 },
#   { grant_id: 4, title: "Test Section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p><p><br></p><p>Jess White:</p><p>Jess White has worked as a grant writer at MIRA for the past two years, and has secured several grants, most recently a six hundred thousand dollar grant from the Office of Refugee Resettlement (ORR). This work inspired her more recent project with MIRA, the creation and implementation of an original grantwriting app that incorporates streamlined grant writing templates and an intuitive grant materials library. This edits also. this edits also and these edits.</p>", sort_order: 1, wordcount: 127 },
# ])

# Report.create!([
#   { grant_id: 1, title: "Letter of Interest: Asian Giving Circle Grants 2020", deadline: "2020-11-24 12:49:00", submitted: false },
#   { grant_id: 1, title: "", deadline: "2020-11-11 23:52:00", submitted: false },
#   { grant_id: 1, title: "Report for Letter of Interest: Asian Giving Circle Grants 2020", deadline: "2020-11-25 12:53:00", submitted: false },
#   { grant_id: 1, title: "Asian Giving Circle Grant Report", deadline: "2020-11-24 11:07:00", submitted: true },
#   { grant_id: 1, title: "Report for Letter of Interest: Asian Giving Circle Grants 2020", deadline: "2020-11-17 13:54:00", submitted: false },
#   { grant_id: 4, title: "Report for Test Grant Sort Order Logic", deadline: "2020-11-17 13:09:00", submitted: false },
# ])
# ReportSection.create!([
#   { report_id: 1, title: "Report Intro", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA, the Middle Eastern Immigrant and Refugee Alliance, was originally founded in 2009 as the Iraqi Mutual Aid Society by newly-arrived Iraqi refugees, in response to the challenges they faced while adapting to their new lives in the United States. MIRA forges connections between Middle Eastern and American society, and facilitates the preservation and exchange of Middle Eastern culture. Our goal is to foster well-being and self-sufficiency for resettled refugees and immigrants from across the Middle East and beyond, and to use our multilingual and multicultural expertise to tailor our services to the unique needs of our clients— whom we serve regardless of gender, religion, ethnicity, nationality, or family size.​Our staff and volunteers speak Arabic, Assyrian, Kurdish, and Farsi. Almost all arrived to the United States as refugees themselves. These linguistic, cultural, and experiential connections with our Middle Eastern clients distinguish MIRA; there is no comparable organization serving this population in the Chicago area. Over the past ten years since the founding, MIRA has expanded to offer services to refugees, immigrants, asylees, and Special Immigrant Visa holders from all over the world, but we are proud to say that this founding spirit has only grown stronger— MIRA continues to be community-driven, refugee-powered, and closely attuned to the needs and voices of the population we serve.</span></p>", sort_order: 1, wordcount: 0 },
#   { report_id: 1, title: "Program Achievements", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 2, wordcount: 0 },
#   { report_id: 5, title: "Test Report section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 1, wordcount: 0 },
#   { report_id: 5, title: "Test Report Section 4", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA helps Middle Eastern refugees and immigrants access the services they need, including public benefits, healthcare, and referrals to partner organizations or other agencies. In FY18-19 MIRA provided 341 Case Management Clients with 677 Case Management Case Activities.</span></p>", sort_order: 4, wordcount: 0 },
#   { report_id: 5, title: "Test Report Section 7", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 7, wordcount: 0 },
#   { report_id: 5, title: "Test Report Section 2", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 2, wordcount: 0 },
#   { report_id: 6, title: "Test Report Section 3", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</span></p>", sort_order: 3, wordcount: 0 },
#   { report_id: 6, title: "Test Report Section 5", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 5, wordcount: 0 },
#   { report_id: 6, title: "Test Report Section 2", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA works with clients to address their educational needs, including assistance applying for college credit and training programs, evaluating educational credentials, and applying for financial aid. In FY18-19 MIRA provided 97 Adult Education Clients with 152 Adult Education Case Activities.</span></p>", sort_order: 2, wordcount: 0 },
#   { report_id: 6, title: "Test Report Section 4", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA offers a variety of support for families with children, including pre-school and school enrollment, working with teachers and administration, support for struggling students, parental support, and monthly Parents’ Groups.&nbsp;In FY18-19 MIRA provided 120 Child and Family Services Clients with 480 Child and Family Services Case Activities.</span></p>", sort_order: 4, wordcount: 51 },
#   { report_id: 6, title: "Test Section 2", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 2, wordcount: 53 },
#   { report_id: 6, title: "Test Section 2", text: "<p><br></p><p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities.</span></p>", sort_order: 2, wordcount: 53 },
#   { report_id: 6, title: "Test Section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA helps Middle Eastern refugees and immigrants access the services they need, including public benefits, healthcare, and referrals to partner organizations or other agencies. In FY18-19 MIRA provided 341 Case Management Clients with 677 Case Management Case Activities.</span></p>", sort_order: 1, wordcount: 42 },
#   { report_id: 5, title: "Test Section Layout", text: "<p><span style=\"color: rgb(102, 102, 102);\">The Middle Eastern Immigrant and Refugee Alliance (MIRA) fosters the well-being and self-sufficiency of Middle Eastern refugees, immigrants, and asylees in Chicago. MIRA serves as a first point of contact for a diverse client population from around the world, offering culturally competent services for those from the Middle East and Islamic cultures. The immigrants and refugees we serve arrive in the United States facing numerous barriers to full integration into society. Our mandate is to provide them with the tools they need to build successful, stable, enriching lives in their new homes. The primary needs of the community relate to navigating American systems for safety net services, employment, and education; integrating into American society while maintaining distinct cultural and community support and traditions; and undertaking the legal processes necessary for continued life in the United States without undue financial burdens or hardships.</span></p>", sort_order: 6, wordcount: 146 },
#   { report_id: 6, title: "Test Report Section 1", text: "<p><span style=\"color: rgb(102, 102, 102);\">MIRA provides the resources and structure for Middle Eastern refugees to support one another and welcome new arrivals with what they need to succeed through support groups, community events, and bridge-building activities with the wider Chicago community. In FY18-19 189 MIRA Community Empowerment Clients participated in 645 Empowerment Activities. Will this update&gt; Will this test work?</span></p>", sort_order: 1, wordcount: 60 },
# ])

# OrganizationUser.create!([
#   {user_id: 8, organization_id: 1},
#   {user_id: 8, organization_id: 2},
#   {user_id: 8, organization_id: 3},
#   {user_id: 8, organization_id: 4},
#   {user_id: 8, organization_id: 5},
#   {user_id: 8, organization_id: 6},
#   {user_id: 8, organization_id: 7},
#   {user_id: 8, organization_id: 8},
#   {user_id: 8, organization_id: 9},
#   {user_id: 8, organization_id: 10},
#   {user_id: 8, organization_id: 12},
#   {user_id: 8, organization_id: 12},
# ])

# create_table "bios", force: :cascade do |t|
#   t.integer "organization_id"
#   t.string "first_name"
#   t.string "last_name"
#   t.text "text"
#   t.datetime "created_at", precision: 6, null: false
#   t.datetime "updated_at", precision: 6, null: false
#   t.string "title"
#   t.integer "wordcount"
# end

Bio.create!([
  {organization_id: 1, title: "Executive Director", first_name: "Elspeth", last_name: "Tascioni", text: "Elspeth Tascioni has worked with MIRA for the past eight years, first as Director of Client Services and most recently as Executive Director. She has over twenty-five years of experience in the nonprofit sector, including five years with the Heartland Health Alliance as Director of Client Services. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At risus viverra adipiscing at in tellus integer feugiat. Nunc congue nisi vitae suscipit tellus mauris a. Vulputate dignissim suspendisse in est. Scelerisque eu ultrices vitae auctor. Cursus sit amet dictum sit amet justo. Eget nunc scelerisque viverra mauris in. Vivamus arcu felis bibendum ut tristique. Aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque purus semper eget duis. Ut aliquam purus sit amet luctus venenatis. Egestas erat imperdiet sed euismod nisi porta. Tempus quam pellentesque nec nam aliquam sem et. Velit egestas dui id ornare. Quam quisque id diam vel quam. Aliquet porttitor lacus luctus accumsan. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Risus at ultrices mi tempus. Et malesuada fames ac turpis.", wordcount: 125},
  {organization_id: 1, title: "Director of Client Services", first_name: "Marilee", last_name: "Cooper", text: "Marilee Cooper has worked with MIRA as Director of Client Services for four years. Previously, she worked as the director of Chicago House's community supported living program, where she was Nunc faucibus a pellentesque sit. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Morbi tristique senectus et netus et malesuada. Euismod lacinia at quis risus sed vulputate odio ut. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Nisi vitae suscipit tellus mauris. Urna id volutpat lacus laoreet non curabitur gravida. Massa placerat duis ultricies lacus. Feugiat nibh sed pulvinar proin gravida hendrerit. Quis commodo odio aenean sed adipiscing diam. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Mattis vulputate enim nulla aliquet porttitor lacus luctus.", wordcount: },
  {organization_id: 1, title: "Director of Legal Services", first_name: "Osman", last_name: "Almasi", text: "Osman Almasi obtainded his law degree from the University of Chicago, and subsequently worked as an associate with Feldman and Associates, the largest immigration law firm in Chicago. He has Sit amet massa vitae tortor condimentum lacinia quis vel. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Amet justo donec enim diam vulputate ut pharetra sit. Sollicitudin nibh sit amet commodo nulla. At varius vel pharetra vel turpis nunc eget lorem dolor. Consequat semper viverra nam libero justo laoreet sit amet cursus. Etiam erat velit scelerisque in dictum non consectetur a. Dui accumsan sit amet nulla facilisi. Cum sociis natoque penatibus et magnis dis parturient. Placerat in egestas erat imperdiet sed. Adipiscing tristique risus nec feugiat in.", wordcount: },
  {organization_id: 1, title: "Director of Education", first_name: "Aminah", last_name: "Husseini", text: "Aminah Husseini has worked for MIRA for twelve years, and is the founder of MIRA's educational programs. She has over ten years of experience as a teacher in the Chicago Public School System, as well as a certificaiton in Ultricies lacus sed turpis tincidunt id. Ac turpis egestas maecenas pharetra convallis posuere. Vitae auctor eu augue ut lectus. Sollicitudin nibh sit amet commodo. Habitant morbi tristique senectus et netus. Pretium quam vulputate dignissim suspendisse in est ante in. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Fusce ut placerat orci nulla pellentesque dignissim. Nulla porttitor massa id neque aliquam vestibulum morbi. Arcu dui vivamus arcu felis bibendum ut tristique et.", wordcount: },
  {organization_id: 1, title: "Office Manager", first_name: "Zaynab", last_name: "Khalifa", text: "Zaynab Khalifa has worked for MIRA since its establishment in 2003, and Fermentum et sollicitudin ac orci. Ultrices mi tempus imperdiet nulla. Habitasse platea dictumst quisque sagittis. In dictum non consectetur a. Varius sit amet mattis vulputate enim nulla. Eget dolor morbi non arcu risus quis. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Id faucibus nisl tincidunt eget nullam. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Ultricies tristique nulla aliquet enim tortor at auctor. Pellentesque adipiscing commodo elit at. Ullamcorper malesuada proin libero nunc consequat interdum varius sit. Leo urna molestie at elementum eu. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Habitasse platea dictumst vestibulum rhoncus. Volutpat consequat mauris nunc congue nisi.", wordcount: },
])

# create_table "boilerplates", force: :cascade do |t|
#   t.integer "organization_id"
#   t.integer "category_id"
#   t.string "title"
#   t.text "text"
#   t.integer "wordcount"
#   t.datetime "created_at", precision: 6, null: false
#   t.datetime "updated_at", precision: 6, null: false
# end

Boilerplate.create!([
  {organization_id: 1, category_id: , title: "Our Mission - Capsule", text: "MIRA is a nonprofit organization serving refugees and immigrants in the Chicago area. Ultricies lacus sed turpis tincidunt id. Ac turpis egestas maecenas pharetra convallis posuere. Vitae auctor eu augue ut lectus. Sollicitudin nibh sit amet commodo. Habitant morbi tristique senectus et netus. Pretium quam vulputate dignissim suspendisse in est ante in. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Fusce ut placerat orci nulla pellentesque dignissim. Nulla porttitor massa id neque aliquam vestibulum morbi. Arcu dui vivamus arcu felis bibendum ut tristique et.", wordcount: },
  {organization_id: 1, category_id: , title: "Our Mission", text: "MIRA serves refugees and immigrants in the Chicago area. Sit amet massa vitae tortor condimentum lacinia quis vel. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Amet justo donec enim diam vulputate ut pharetra sit. Sollicitudin nibh sit amet commodo nulla. At varius vel pharetra vel turpis nunc eget lorem dolor. Consequat semper viverra nam libero justo laoreet sit amet cursus. Etiam erat velit scelerisque in dictum non consectetur a. Dui accumsan sit amet nulla facilisi. Cum sociis natoque penatibus et magnis dis parturient. Placerat in egestas erat imperdiet sed. Adipiscing tristique risus nec feugiat in.", wordcount: },
  {organization_id: 1, category_id: , title: "Financial Literacy Workshops", text: "MIRA provides financial literacy workshops to recent immigrants and refugees. These workshops are offered onsite by employees who are all native speakers of Arabic. Nunc faucibus a pellentesque sit. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Morbi tristique senectus et netus et malesuada. Euismod lacinia at quis risus sed vulputate odio ut. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Nisi vitae suscipit tellus mauris. Urna id volutpat lacus laoreet non curabitur gravida. Massa placerat duis ultricies lacus. Feugiat nibh sed pulvinar proin gravida hendrerit. Quis commodo odio aenean sed adipiscing diam. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Mattis vulputate enim nulla aliquet porttitor lacus luctus.", wordcount: },
  {organization_id: 1, category_id: , title: "Achievements 2021", text: "In 2021, MIRA provided services to a total of 4081 clients, including Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At risus viverra adipiscing at in tellus integer feugiat. Nunc congue nisi vitae suscipit tellus mauris a. Vulputate dignissim suspendisse in est. Scelerisque eu ultrices vitae auctor. Cursus sit amet dictum sit amet justo. Eget nunc scelerisque viverra mauris in. Vivamus arcu felis bibendum ut tristique. Aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque purus semper eget duis. Ut aliquam purus sit amet luctus venenatis. Egestas erat imperdiet sed euismod nisi porta. Tempus quam pellentesque nec nam aliquam sem et. Velit egestas dui id ornare. Quam quisque id diam vel quam. Aliquet porttitor lacus luctus accumsan. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Risus at ultrices mi tempus. Et malesuada fames ac turpis.", wordcount: },
  {organization_id: 1, category_id: , title: "History", text: "MIRA was established in 2003 to provide assistance to refugees and immigrants in the Chicago area. Since then Fermentum et sollicitudin ac orci. Ultrices mi tempus imperdiet nulla. Habitasse platea dictumst quisque sagittis. In dictum non consectetur a. Varius sit amet mattis vulputate enim nulla. Eget dolor morbi non arcu risus quis. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Id faucibus nisl tincidunt eget nullam. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Arcu felis bibendum ut tristique et egestas quis ipsum suspendisse. Ultricies tristique nulla aliquet enim tortor at auctor. Pellentesque adipiscing commodo elit at. Ullamcorper malesuada proin libero nunc consequat interdum varius sit. Leo urna molestie at elementum eu. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Habitasse platea dictumst vestibulum rhoncus. Volutpat consequat mauris nunc congue nisi.", wordcount: },
])

# create_table "categories", force: :cascade do |t|
#   t.integer "organization_id"
#   t.string "name"
#   t.datetime "created_at", precision: 6, null: false
#   t.datetime "updated_at", precision: 6, null: false
# end

Category.create!([
  {organization_id: 1, name: "Who We Are",},
  {organization_id: 1, name: "Our Clients",},
  {organization_id: 1, name: "Our Mission",},
  {organization_id: 1, name: "Programs",},
  {organization_id: 1, name: "Education",},
  {organization_id: 1, name: "Financial Literacy",},
  {organization_id: 1, name: "Legal Services",},
  {organization_id: 1, name: "Cultural Events",},
])

# create_table "funding_orgs", force: :cascade do |t|
#   t.string "website"
#   t.string "name"
#   t.integer "organization_id"
#   t.datetime "created_at", precision: 6, null: false
#   t.datetime "updated_at", precision: 6, null: false
# end

FundingOrg.create!([
  {organization_id: 1, name: "Chicago Refugee Association", website: "cra.org"},
  {organization_id: 1, name: "Great Lakes Mutual Aid Foundation", website: "greatlakesmaf.org"},
  {organization_id: 1, name: "Welcome Home Foundation", website: "welcomehomefoundation.org"},
  {organization_id: 1, name: "Illinois Refugee Assistance", website: "illinoisrefugeeassist.org"},
  {organization_id: 1, name: "Quinn-McCormick Foundation", website: "quinnmccormick.org"},
])

# create_table "grants", force: :cascade do |t|
#   t.integer "organization_id"
#   t.string "title"
#   t.integer "funding_org_id"
#   t.string "rfp_url"
#   t.datetime "deadline"
#   t.boolean "submitted"
#   t.boolean "successful"
#   t.datetime "created_at", precision: 6, null: false
#   t.datetime "updated_at", precision: 6, null: false
#   t.string "purpose"
# end

Grant.create!([
  {organization_id: 1, title: "Financial Literacy Grants - 2021", purpose: "financial literacy", funding_org_id: "", rfp_url: "", deadline: "2021-11-24 11:07:00", submitted: false, successful: false},
  {organization_id: 1, title: "General Funding Grant - June 2021", purpose: "general funding", funding_org_id: "", rfp_url: "", deadline: "2021-11-24 11:07:00", submitted: false, successful: false},
  {organization_id: 1, title: "Pre-K Enrichment Grant - 2020-2021", purpose: "education", funding_org_id: "", rfp_url: "", deadline: "2021-11-24 11:07:00", submitted: false, successful: false},
  {organization_id: 1, title: "Cultural Events Grant - 2021", purpose: "cultural programming", funding_org_id: "", rfp_url: "", deadline: "2021-11-24 11:07:00", submitted: false, successful: false},
  {organization_id: 1, title: "General Funding and Operations Grant - 2021", purpose: "general funding", funding_org_id: "", rfp_url: "", deadline: "2021-11-24 11:07:00", submitted: false, successful: false},
])

# create_table "sections", force: :cascade do |t|
#   t.integer "grant_id"
#   t.string "title"
#   t.text "text"
#   t.integer "sort_order"
#   t.datetime "created_at", precision: 6, null: false
#   t.datetime "updated_at", precision: 6, null: false
#   t.integer "wordcount"
# end

Section.create!([
  {},
])

Section.create!([
  {},
])

# create_table "reports", force: :cascade do |t|
#   t.integer "grant_id"
#   t.string "title"
#   t.datetime "deadline"
#   t.boolean "submitted"
#   t.datetime "created_at", precision: 6, null: false
#   t.datetime "updated_at", precision: 6, null: false
# end

Report.create!([
  {},
])

# create_table "report_sections", force: :cascade do |t|
#   t.integer "report_id"
#   t.string "title"
#   t.text "text"
#   t.integer "sort_order"
#   t.datetime "created_at", precision: 6, null: false
#   t.datetime "updated_at", precision: 6, null: false
#   t.integer "wordcount"
# end

ReportSection.create!([
  {},
])

ReportSection.create!([
    {},
    ])

  # OrganizationUser.create!([
#   {user_id: 8, organization_id: 1},
#   {user_id: 8, organization_id: 2},
#   {user_id: 8, organization_id: 3},
#   {user_id: 8, organization_id: 4},
#   {user_id: 8, organization_id: 5},
#   {user_id: 8, organization_id: 6},
#   {user_id: 8, organization_id: 7},
#   {user_id: 8, organization_id: 8},
#   {user_id: 8, organization_id: 9},
#   {user_id: 8, organization_id: 10},
#   {user_id: 8, organization_id: 12},
#   {user_id: 8, organization_id: 12},
# ])